PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE tag (id integer primary key, name char(30));
INSERT INTO tag VALUES(1,'Yarns');
INSERT INTO tag VALUES(2,'Patterns');
INSERT INTO tag VALUES(3,'Techniques');
INSERT INTO tag VALUES(4,'Finished products');
INSERT INTO tag VALUES(5,'Other');
CREATE TABLE post (id integer primary key, user_id char(20), time datetime, title text, content text);
CREATE TABLE comment (id integer primary key, post_id integer, user_id char(20), time datetime, content text);
CREATE TABLE feedback (id integer primary key, post_id integer, comment_id integer, user_id char(20), type char(1));
CREATE TABLE post_tag (id integer primary key, post_id integer, tag_id integer);
CREATE TABLE user (id char(20) primary key, email char(254), password text);
CREATE TABLE session (id char(64) primary key, user_id char(20), expires datetime);
COMMIT;
