name: Build, Push, and Deploy to K3s
on:
  push:
    branches: [master]

jobs:
  build-deploy:
    runs-on: self-hosted

  build-deploy:
    runs-on: self-hosted

    env:
      IMAGE_NAME: maxtech470/project101
      K8S_NAMESPACE: forum
<<<<<<< HEAD
      K8S_NAMESPACE: forum
=======
      MY_SECRET_CODE: ${{ secrets.MY_SECRET_CODE }}
>>>>>>> b5888cd89c9c4f86bae2a688fe35577e96592a56

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
<<<<<<< HEAD
      - name: Checkout code
        uses: actions/checkout@v3

=======
        
>>>>>>> b5888cd89c9c4f86bae2a688fe35577e96592a56
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Set up JDK 17 (required for Nexus step)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up JDK 17 (required for Nexus step)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Go tests and generate coverage report
        run: |
          go test ./... -coverprofile=coverage.out
      - name: Run Go tests and generate coverage report
        run: |
          go test ./... -coverprofile=coverage.out

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Get next semantic version tag
        id: get_tag
        run: |
          tags=$(curl -s https://hub.docker.com/v2/repositories/${IMAGE_NAME}/tags/?page_size=100 | jq -r '.results[].name' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V)
          if [ -z "$tags" ]; then
            next="v1.0.0"
          else
            latest=$(echo "$tags" | tail -n 1)
            major=$(echo $latest | cut -d. -f1 | sed 's/v//')
            minor=$(echo $latest | cut -d. -f2)
            patch=$(echo $latest | cut -d. -f3)
            patch=$((patch + 1))
            next="v${major}.${minor}.${patch}"
          fi
          echo "tag=$next" >> $GITHUB_OUTPUT
      - name: Get next semantic version tag
        id: get_tag
        run: |
          tags=$(curl -s https://hub.docker.com/v2/repositories/${IMAGE_NAME}/tags/?page_size=100 | jq -r '.results[].name' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V)
          if [ -z "$tags" ]; then
            next="v1.0.0"
          else
            latest=$(echo "$tags" | tail -n 1)
            major=$(echo $latest | cut -d. -f1 | sed 's/v//')
            minor=$(echo $latest | cut -d. -f2)
            patch=$(echo $latest | cut -d. -f3)
            patch=$((patch + 1))
            next="v${major}.${minor}.${patch}"
          fi
          echo "tag=$next" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:${{ steps.get_tag.outputs.tag }} .
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:${{ steps.get_tag.outputs.tag }} .

      - name: Tag image as latest
        run: docker tag $IMAGE_NAME:${{ steps.get_tag.outputs.tag }} $IMAGE_NAME:latest
      - name: Tag image as latest
        run: docker tag $IMAGE_NAME:${{ steps.get_tag.outputs.tag }} $IMAGE_NAME:latest

      - name: Push Docker images
        run: |
          docker push $IMAGE_NAME:${{ steps.get_tag.outputs.tag }}
          docker push $IMAGE_NAME:latest
      - name: Push Docker images
        run: |
          docker push $IMAGE_NAME:${{ steps.get_tag.outputs.tag }}
          docker push $IMAGE_NAME:latest

      - name: Build Go binary
        run: |
          mkdir -p dist
          go build -o dist/forum-docker .

      - name: Upload artifact to Nexus
        run: |
          curl -v -u "${{ secrets.NEXUS_USER }}:${{ secrets.NEXUS_PASSWORD }}" \
          --upload-file dist/forum-docker \
          "http://localhost:8081/repository/go-artifacts/forum-docker-${{ steps.get_tag.outputs.tag }}"

      - name: Setup kubectl
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml
          kubectl version --client
          kubectl config current-context

      - name: Create namespace if not exists
        run: |
          export KUBECONFIG=$PWD/kubeconfig.yaml
          kubectl apply -f - <<EOF
          apiVersion: v1
          kind: Namespace
          metadata:
            name: ${K8S_NAMESPACE}
          EOF

      - name: Deploy app manifests to K3s
        env:
          MY_SECRET_CODE: ${{ secrets.MY_SECRET_CODE }}
        run: |
          export KUBECONFIG=$PWD/kubeconfig.yaml

          cat <<EOF | kubectl apply -f -
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: forum-app
            namespace: ${K8S_NAMESPACE}
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: forum
            template:
              metadata:
                labels:
                  app: forum
              spec:
                containers:
                  - name: forum
                    image: ${IMAGE_NAME}:${{ steps.get_tag.outputs.tag }}
                    ports:
                      - containerPort: 8080
          EOF

          cat <<EOF | kubectl apply -f -
          apiVersion: v1
          kind: Service
          metadata:
            name: forum-service
            namespace: ${K8S_NAMESPACE}
          spec:
            selector:
              app: forum
            ports:
              - port: 80
                targetPort: 8080
            type: ClusterIP
          EOF

          cat <<EOF | kubectl apply -f -
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: forum-ingress
            namespace: ${K8S_NAMESPACE}
            annotations:
              nginx.ingress.kubernetes.io/rewrite-target: /
          spec:
            ingressClassName: nginx
            rules:
              - http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: forum-service
                          port:
                            number: 80
          EOF