name: Tag and Push Docker Image

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: maxtech470/project101

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Get next semantic version tag
      id: get_tag
      run: |
        tags=$(curl -s https://hub.docker.com/v2/repositories/${IMAGE_NAME}/tags/?page_size=100 | jq -r '.results[].name' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V)
        
        if [ -z "$tags" ]; then
          next="v1.0.0"
        else
          latest=$(echo "$tags" | tail -n 1)
          major=$(echo $latest | cut -d. -f1 | sed 's/v//')
          minor=$(echo $latest | cut -d. -f2)
          patch=$(echo $latest | cut -d. -f3)
          patch=$((patch + 1))
          next="v${major}.${minor}.${patch}"
        fi

        echo "Next tag: $next"
        echo "tag=$next" >> $GITHUB_OUTPUT

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME:${{ steps.get_tag.outputs.tag }} .

    - name: Push Docker image
      run: docker push $IMAGE_NAME:${{ steps.get_tag.outputs.tag }}

